server:
  port: 8888

app:
  search-radius-meters: 1000
  plugin:
    region:
      nominatim:
        base-url: "https://nominatim.openstreetmap.org/search"
    subway:
      overpass:
        base-url: "https://www.overpass-api.de/api/interpreter"
    location:
      internal:
        base-url: "internal-resource-url"

