server:
  port: 8888
  servlet:
    context-path: /subway_service

spring:
  application:
    name: subway_service
  cache:
    cache-names: subways
    caffeine:
      spec: maximumSize=100,expireAfterAccess=43200s

app:
  plugin:
    region:
      nominatim:
        base-url: "https://nominatim.openstreetmap.org/search"
    subway:
      overpass:
        base-url: "https://www.overpass-api.de/api/interpreter"
    location:
      internal:
        base-url: "internal-resource-url"
